Repository ti-broish/api, pull requests merged in 2023-02, with the labels that each got.

#146 Fix auth bug
  src/firebase/auth/passport-firebase.strategy.ts
  src/me/api/me.controller.ts
Labels: проблем

#149 Протоколи без аутентикация
  src/migrations/1676252731919-MakeProtocolActionsActorOptional.ts
  src/protocols/api/protocols.controller.ts
  src/protocols/entities/protocol-action.entity.ts
  src/protocols/entities/protocol.entity.ts
  src/protocols/entities/protocols.repository.ts
Labels: протоколи

#155 Update firebase token script
  package-lock.json
  package.json
  scripts/get-token.js
Labels: проблем

#157 Протоколи без секция
  src/migrations/1676413609314-MakeProtocolsSectionOptional.ts
  src/protocols/api/protocol.dto.ts
  src/protocols/api/protocols.controller.ts
  src/protocols/entities/protocol.entity.ts
  src/protocols/entities/protocols.repository.ts
Labels: протоколи

#156 Оправяне на сийдването на организации
  src/migrations/1676411442647-MakeOrganizationsIsHiddenDefaultToBoolean.ts
Labels: проблем

#148 Списък със сигнали без автор в админа
  src/violations/api/violation.dto.ts
  src/violations/api/violations-filters.dto.ts
  src/violations/api/violations.controller.ts
  src/violations/entities/violation-update.entity.ts
  src/violations/entities/violations.repository.ts
  src/violations/violations.module.ts
Labels: сигнали

#159 Fix sections filter by city region filter using query builder
  src/sections/entities/sections.repository.ts
Labels: проблем, данни

#158 Add recaptcha (PR #132)
  .env.schema
  README.md
  package-lock.json
  package.json
  src/app.module.ts
  src/config/cors.config.ts
  src/config/schema.config.ts
  src/pictures/api/pictures.controller.ts
  src/protocols/api/protocols.controller.ts
  src/violations/api/violations.controller.ts
Labels: резултати

#162 Fix protocol section replacement and loading
  src/protocols/api/protocol.dto.ts
  src/protocols/entities/protocol.entity.ts
  src/protocols/entities/protocols.repository.ts
Labels: проблем, протоколи

#163 Add risk level to sections
  src/migrations/1676594664001-AddSectionsRiskyLevel.ts
  src/results/api/results.controller.ts
  src/results/api/stats.dto.ts
  src/sections/api/section.dto.ts
  src/sections/entities/section.entity.ts
  src/sections/entities/sections.repository.ts
Labels: резултати, данни

#165 Risky sections seed
  package.json
  src/config/typeorm-seeds.datasource.ts
  src/seeds/1676787373554-RiskySections.ts
  src/seeds/risky_sections.csv
Labels: данни

#160 Use postgres pessimistic lock when picking items from the queue
  src/protocols/entities/work-items.repository.ts
Labels: протоколи

#172 Remove unused @nestjs/schedule package after removing broadcasts
  package-lock.json
  package.json
  src/app.module.ts
Labels: dependencies

#173 Fix usage of pessimistic lock in queue by adding transactions
  src/protocols/api/protocols.controller.ts
  src/protocols/api/work-queue.service.ts
  src/protocols/entities/work-items.repository.ts
Labels: проблем, протоколи
